name: 'Publish'

on:
  release:
    types: [published]
  push:
    branches:
      - master

env:
  GIT_TAG_NAME: dev

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - uses: olegtarasov/get-tag@v2
      if: github.event_name == 'release'
      name: Set tag envronment variable

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish builder
      uses: home-assistant/builder@master
      with:
        args: |
          --amd64 --armv7 --aarch64 \
          --target /data \
          --generic $GIT_TAG_NAME