name: 'Test'

on:
  pull_request:

jobs:
  build:
    name: Test action build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Build builder
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --amd64 \
          --target /data \
          --generic latest

    - name: Test builder
      uses: ./
      with:
        args: |
          --test \
          --amd64 --armv7 --aarch64 \
          --target /data \
          --generic ${{ github.sha }}